# 우아한 사이파이

##  Chapter 우아한 넘파이 : 파이썬 과학 기초 

In [20]:
import numpy as np

def rpkm(counts, lengths):
    N = np.sum(counts, axis = 0)
    L = lengths
    C = counts
    normed = 10^9 * C / (N[np.newaxis, :] * L[:, np.newaxis]) # IndexError: invalid index to scalar variable.
    return(normd)

### 1.1 유전자 발현과 데이터

In [21]:
gene0 = [100, 200]
gene1 = [50, 0]
gene2 = [350, 100]
expression_data = [gene0, gene1, gene2]

expression_data[2][0]

350

### 1.2 넘파이 N차원 배열

In [22]:
import numpy as np
array1d = np.array([1,2,3,4])
print(array1d)

[1 2 3 4]


In [23]:
print(type(array1d))

<class 'numpy.ndarray'>


In [24]:
print(array1d.shape)

(4,)


- array1d.shape는 한 숫자를 갖는 tuple.
- len 은 2차원 배열에서 사용할 수 있다.

In [25]:
array2d = np.array(expression_data)

print(array2d)
print(array2d.shape)
print(type(array2d))

[[100 200]
 [ 50   0]
 [350 100]]
(3, 2)
<class 'numpy.ndarray'>


In [26]:
print(array2d.ndim) # 배열의 차원을 확인

2


#### 1.2.1 왜 파이썬 리스트 대신 ndarray를 사용할까?

In [27]:
import numpy as np

array = np.arange(1e6)

list_array = array.tolist()

In [29]:
%timeit -n10 y = [val * 5 for val in list_array]

71.7 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
%timeit -n19 x = array * 5

521 µs ± 342 µs per loop (mean ± std. dev. of 7 runs, 19 loops each)


In [31]:
x = np.array([1,2,3], np.int32)
print(x)

[1 2 3]


In [32]:
y = x[:2]
print(y)

[1 2]


In [33]:
y[0] = 6
print(y)

[6 2]


In [34]:
print(x)

[6 2 3]


In [35]:
y = np.copy(x[:2])

In [36]:
print(y)

[6 2]


#### 1.2.2 벡터화

In [37]:
x = np.array([1,2,3,4])
print(x * 2)

[2 4 6 8]


In [39]:
y = np.array([0,1,2,1])
print(x + y)

[1 3 5 5]


#### 1.2.3 브로드캐스팅

- 브로드캐스팅 : 두 배열 간 암묵적 연산을 수행

In [41]:
x = np.array([1,2,3,4])
x = np.reshape(x, (len(x), 1))
print(x)

[[1]
 [2]
 [3]
 [4]]


In [42]:
y = np.array([0,1,2,1])
y = np.reshape(y, (1, len(y)))
print(y)

[[0 1 2 1]]


In [43]:
print(x.shape)
print(y.shape)

(4, 1)
(1, 4)


In [44]:
outer = x * y
print(outer)

[[0 1 2 1]
 [0 2 4 2]
 [0 3 6 3]
 [0 4 8 4]]


In [45]:
print(outer.shape)

(4, 4)


- outer[i, j] = x[i] * y[j]  
- (i,j)
- 두 배열의 차원이 다른 경우, 다른 배열의 차원과 일치하도록 한 배열에서 차원을 암묵적으로 확장한다.

### 1.3 유전자 발현 데이터셋

In [52]:
import numpy as np
import pandas as pd

# filename = 'https://raw.githubusercontent.com/AstinCHOI/elegant-scipy/master/data/counts.txt'
filename = '/Users/chosikc/Sites/elegant_scipy/counts.txt'
with open(filename, 'rt') as f:
    data_table = pd.read_csv(f, index_col = 0)
    
print(data_table.iloc[:5, :5])

       00624286-41dd-476f-a63b-d2a5f484bb45  TCGA-FS-A1Z0  TCGA-D9-A3Z1  \
A1BG                                1272.36        452.96        288.06   
A1CF                                   0.00          0.00          0.00   
A2BP1                                  0.00          0.00          0.00   
A2LD1                                164.38        552.43        201.83   
A2ML1                                 27.00          0.00          0.00   

       02c76d24-f1d2-4029-95b4-8be3bda8fdbe  TCGA-EB-A51B  
A1BG                                 400.11        420.46  
A1CF                                   1.00          0.00  
A2BP1                                  0.00          1.00  
A2LD1                                165.12         95.75  
A2ML1                                  0.00          8.00  


#### 1.3.1 팬더스로 데이터 읽기

### 1.4 정규화

#### 1.4.1 샘플 간 비교

#### 1.4.2 샘플 간 공간 크기 정규화

#### 1.4.3 유전자 간 비교

#### 1.4.4 샘플과 유전자의 정규화 : RPKM

### 1.5 마치며